version: '3.8'

services:
  db:
    image: mysql
    container_name: fifadb
    restart: always
    #command: mysql -u 
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: fifa
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
    ports:
      - 3306:3306
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
  app:
    build: .
    command: npm run start
    volumes: 
      - ./:/code
    ports: 
      - 3000:3000
    depends_on: 
      - db
    
