version: '3.8'

services:
  db:
    image: mysql
    container_name: fifadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: fifa
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
    ports:
      - 3306:3306
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    